### ISSUE TITLE
MbedTLS had build errors in julia 0.4

### ISSUE THREAD

**Issue by yfractal** [JuliaWeb/MbedTLS.jl#102]
`Mux.jl` depends `MbedTLS.jl` and it run tests in julia 0.4 by CI.
But the CI fails because of [MbedTLS had build errors](https://travis-ci.org/JuliaWeb/Mux.jl/jobs/227337250#L255).

Does MbedTLS support julia 0.4 now?

**Comment by tkelman** [comment]
Prior versions did, master does not. That's a cache server failure, cc @staticfloat

**Comment by staticfloat** [comment]
This is weird; it's actually failing on the _second_ download; e.g. the fastly/AWS server connection.  Steps to reproduce:

```
$ docker run -ti quay.io/travisci/travis-ruby /bin/bash
root@1b0d11fe155c:/# curl -v -L -o /dev/null 'https://julialangcache-s3.julialang.org/'
* About to connect() to julialangcache-s3.julialang.org port 443 (#0)
*   Trying 151.101.54.49...   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0connected
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS alert, Server hello (2):
{ [data not shown]
* error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
* Closing connection #0
curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
```

Connecting directly to S3 works however:
```
root@1b0d11fe155c:/# curl -v -L -o /dev/null 'https://julialangcache.s3.amazonaws.com/'
... Lots of happy output ....
```

This is due to the fact that Fastly only supports TLS (and, [starting today, only TLS version 1.2+](https://www.fastly.com/blog/phase-two-our-tls-10-and-11-deprecation-plan)) and the `curl` that comes with the `precise` images of Travis are too old to support this; they only support TLS 1.0.

**Comment by tkelman** [comment]
Good digging. Guess we could maybe do checksum verification but disable certificate checking in the curl call, would that help?

**Comment by staticfloat** [comment]
We can also run this:
```
$ sudo apt-get update && sudo apt-get upgrade -y libssl1.0.0
```

That is sufficient to get `libssl1.0.0` updated to the point that it'll talk to our servers.

**Comment by tkelman** [comment]
oh, ubuntu backported that? could try using the apt addon https://docs.travis-ci.com/user/installing-dependencies/#Adding-APT-Packages to avoid needing platform conditionals around it

**Comment by staticfloat** [comment]
Yes, and that is also supposed to work when you don't have `sudo` access I think.

**Comment by tkelman** [comment]
right. and sooner or later travis may change their default to 14.04, though I wonder whether people on centos 6 or other similarly old distros may have issues here. python was complaining at me about something related a while back, I forget the exact details though.

**Comment by yfractal** [comment]
@tkelman 
Hi, thanks for your reply.
I guess 0.3.0 is the newest version which supports Julia 0.4, is that right?

**Comment by staticfloat** [comment]
> I wonder whether people on centos 6 or other similarly old distros may have issues here.

If I `docker run -ti centos:6`, I can `curl` just fine, so I think it's just a matter of people upgrading their outdated distros.  `centos:5` doesn't work though, and I can't `yum update` to see if it's been backported because it looks like [CentOS 5 is officially EOL'ed](https://wiki.centos.org/FAQ/General#head-fe8a0be91ee3e7dea812e8694491e1dde5b75e6d) and the repos are gone.

**Comment by tkelman** [comment]
And the buildbots are indeed hitting this. Not good.

**Comment by samoconnor** [comment]
@quinnj obsolete issue? should be closed?
