### ISSUE TITLE
strip error with Linux .so binaries 

### ISSUE THREAD

**Issue by samoconnor** [JuliaWeb/MbedTLS.jl#140]
When I try to strip the `libmbedtls.so.2.7.1` and `libmbedx509.so.2.7.1` I get a "Not enough room for program headers" error:

```bash
bash-4.2# strip libmbedcrypto.so.2.7.1

bash-4.2# strip libmbedtls.so.2.7.1
BFD: stVd9Y98: Not enough room for program headers, try linking with -N
strip:stVd9Y98[.hash]: Bad value
BFD: stVd9Y98: Not enough room for program headers, try linking with -N
strip:stVd9Y98: Bad value

bash-4.2# strip libmbedx509.so.2.7.1
BFD: stEj7Go5: Not enough room for program headers, try linking with -N
strip:stEj7Go5[.hash]: Bad value
BFD: stEj7Go5: Not enough room for program headers, try linking with -N
strip:stEj7Go5: Bad value
```

The platform is Amazon Linux per this Dockerfile: https://github.com/samoconnor/AWSLambda.jl/blob/06_branch/docker/lambdajlbuild/Dockerfile
(and in turn, this one: https://github.com/samoconnor/lambdajl/blob/master/Dockerfile and this one: https://github.com/lambci/docker-lambda)

I can strip all the other `.so` files on the system without a problem:
```Dockerfile
RUN for f in $(find . -name '*.so'); do strip $f ; done
```

**Comment by samoconnor** [comment]
@staticfloat could this be related to the new BinaryBuilder ?

**Comment by staticfloat** [comment]
Yeah, this is because we use `patchelf` to rewrite RPATHs and things like that within the ELF files, and [`patchelf` is known](https://github.com/NixOS/patchelf/issues/10) to play it a little fast-and-loose with things within the ELF headers, causing further processing (like that with `strip`) to throw up its hands and say "I don't know what to do with this binary".

Is there a reason you need to `strip` the binaries?  Most of the time, a `make install` step should be stripping the binaries, so I suggest you try `strip`'ing them after you install, but before you finish the BinaryBuilder build script, which is when libraries will get `patchelf` sic'ed on them.

**Comment by samoconnor** [comment]
Thanks for the link to https://github.com/NixOS/patchelf/issues/10.

I strip all the `.so` files before creating a deployment archive in my [`AWSLambda.jl` Dockerfile](https://github.com/samoconnor/AWSLambda.jl/blob/06_branch/docker/lambdajlbuild/Dockerfile#L98).
Without the `strip` the .ZIP file is 38M, after the `strip`, 30M. I haven't spent time figuring out which `.so` files are worth stripping, I just do `find . -name '*.so' | xargs strip`.

**Comment by staticfloat** [comment]
Yeah, it looks like `MbedTLS` doesn't automatically strip the libraries it installs.  If you want them stripped, I suggest adding a `cd $prefix/lib; for f in $(find . -name '*.so'); do strip $f ; done` to the end of your MBedTLSBuilder script.

**Comment by quinnj** [comment]
will be fixed by #142

**Comment by samoconnor** [comment]
Will the fix be in MbedTLSBuilder.jl or MbedTLS.jl ?

**Comment by quinnj** [comment]
MbedTLSBuilder.jl has already produced stripped binaries as of the v0.7 release. the PR mentioned (#142) updates the MbedTLS.jl build.jl to pull from that new release.

**Comment by samoconnor** [comment]
Ok, nice one. I've made a note to remove the workaround from the AWSLambda.jl Dockerfile at some point when the new versions are tagged etc.
