### ISSUE TITLE
new handshake changes appear to be throwing ECONNRESET unexpectedly 

### ISSUE THREAD

**Issue by s2maki** [JuliaWeb/MbedTLS.jl#148]
When using 1c8c0a1 and trying to make several calls to AWS in quick succession, I am seeing the following error:

```
ERROR (unhandled task failure): read: connection reset by peer (ECONNRESET)
Stacktrace:
 [1] try_yieldto(::Base.##296#297{Task}, ::Task) at ./event.jl:189
 [2] wait() at ./event.jl:234
 [3] wait(::Condition) at ./event.jl:27
 [4] macro expansion at /home/jrun/.julia/v0.6/MbedTLS/src/ssl.jl:188 [inlined]
 [5] (::MbedTLS.##36#37{MbedTLS.SSLContext})() at ./event.jl:73
```

The line in question (ssl.jl:188) appears to be waiting on a Condition (`ctx.bio.readnotify`) , but somehow it ends up throwing an `ECONNRESET` in some cases.

While it does appear from the Julia source that this Condition is allowed to throw exceptions, there is no handler for it since this is happening in a `@schedule`.  Separately, I'm not sure why the `ECONNRESET` is occurring in the first place.  If I roll back to v0.5.8, there are no errors for the same sequence of AWS calls.

This is in Julia 0.6 on Linux.

**Comment by quinnj** [comment]
@samoconnor ^^

**Comment by samoconnor** [comment]
https://github.com/JuliaWeb/MbedTLS.jl/blob/1c8c0a1b8d0e4baa1774a44794447659fd91124b/src/ssl.jl#L183-L190

It seems that the `readnotify` `Condition` can throw a `UVError` in [`uv_readcb (base/stream.jl:485)`](https://github.com/JuliaLang/julia/blob/v0.6.2/base/stream.jl#L485) when libuv signals a fatal connection error to the read callback.

The usual place that waits on `readnotify` is [`wait_readnb`](https://github.com/JuliaLang/julia/blob/v0.6.2/base/stream.jl#L296) (called by the various other Base read functions). My guess is that the `ECONNRESET` was previously showing up as a read error and was handled transparently by the retry loops in HTTP.jl / AWSCore.jl.

The intention of the `@schedule while isopen...` task is to keep the connection active in libuv so that TLS `close_notify` messages can be processed even if there is no other activity on the connection. We're calling `wait(ctx.bio.readnotify)` as a convenient way to sleep most of the time. 
[`start_reading` is a no-op when the connection is already active](https://github.com/JuliaLang/julia/blob/v0.6.2/base/stream.jl#L672-L673), so I guess we could replace the `wait` call with `sleep(1)`. However, it should be sufficient to simply ignore the error thrown by `wait`. i.e. `try wait(ctx.bio.readnotify) end`. 

See pull request https://github.com/JuliaWeb/MbedTLS.jl/pull/149
@vtjnash, @quinnj does this seem right to you?

Related: https://github.com/JuliaWeb/HTTP.jl/pull/236/files

**Comment by quinnj** [comment]
#149 was merged; please report if that solves the issue here or if it's still reproducible.

**Comment by s2maki** [comment]
The error is no longer being thrown.  However, I am seeing (on Linux with a "high"* volume of HTTPS requests going out to DynamoDB), I am seeing a considerable sluggishness.  It's as though the ECONNRESET error is occurring a lot and it's causing excessive retries.

*a few dozen per second; nothing crazy, and this is probably still considered "low" to most people these days.

**Comment by samoconnor** [comment]
Hi @s2maki,

It might help to set some HTTP.jl Connection Pool options [here in `AWSCore.jl/src/http.jl`](https://github.com/JuliaCloud/AWSCore.jl/blob/master/src/http.jl#L46).


In the HTTP.jl test that does "high" volume S3 transfers we set [`reuse_limit = 90`](https://github.com/JuliaWeb/HTTP.jl/blob/master/test/async.jl#L99) to ensure that we hang up on S3 rather than waiting for S3 to hang up on us.

A good starting point might be to set `pipeline_limit=0` (disabled), `reuse_limit=16` (default no limit) an `connection_limit=32` (default 8).

If things run smoothly like this, then try higher values of `reuse_limit` and `connection_limit`.
After that, allowing some amount of pipelining may be beneficial, but only if you have multiple concurrent `@async` tasks, and probably only if you've already set `connection_limit` as high as is practical. 

> Connection Pool options
> - `connection_limit = 8`, number of concurrent connections to each host:port.
> - `pipeline_limit = 16`, number of concurrent requests per connection.
> - `reuse_limit = nolimit`, number of times a connection is reused after the
>                            first request.
> _https://github.com/JuliaWeb/HTTP.jl/blob/master/src/HTTP.jl#L95-L100_

I'm not sure if there is a general solution to connection pool tuning for AWSCore.jl.
It seems like setting `reuse_limit` to something less than 100 is probably a good thing for most AWS services. However, suitable settings for `connection_limit` and `pipeline_limit` are more dependant on the particular application use case. A system hosted on AWS talking to other AWS services in the same region will probably benefit from a high `connection_limit`. Wheres a mobile system running through a high latency wireless internet connection will benefit more from pipelining and a lower `connection_limit`.

Some options:
 - Support configuration of the HTTP.jl ConnectionPool options through the AWSCore `aws` config dict.
 - Make the global ConnectionPool defaults dynamically configurable in HTTP.jl so that users can adjust them before calling AWSCore.
 - Assume that most AWSCore users are building stuff that runs on AWS and optimise connection pool options for that use case in AWSCore.jl/src/http.jl.
 - Add a high-level boolean option to HTTP.jl (or AWSCore.jl) to "optimise for fast local HTTP connections" or "optimise for slow remote HTTP connections".

@quinnj @vtjnash any thoughts?

**Comment by quinnj** [comment]
@s2maki any additional thoughts here? Were you able to try some of @samoconnor 's suggestions for connection management in HTTP.jl?
